### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DasPossum2** [kontron/redmine_oauth#10]
Hello,

do I need a P2 license to connect the plug-in to Azure AD?

My Error:

** Invoke redmine_oauth:email:receive_imap (first_time) ** Invoke environment (first_time) ** Execute environment ** Execute redmine_oauth:email:receive_imap AUTHENTICATE failed.

Best regards

Andy

**Comment by picman** [comment]
I'm not an expert on Microsoft licenses but I think that the problem is in Azure AD configuration. Have you read the README and configured your Azure AD accordingly?

**Comment by picman** [comment]
I have already seen the error in the original post and can only repeat that the problem is in the Azure AD configuration and not in licensing.
