### ISSUE TITLE
Error when executing `rake redmine_oauth:email:receive_imap`

### ISSUE THREAD

**Issue by 7evenk** [kontron/redmine_oauth#11]
I'm trying to execute the command `rake redmine_oauth:email:receive_imap username='notifications@example.com' RAILS_ENV="production"` on my Redmine application, but I'm getting an error message: "wrong number of arguments (given 3, expected 2)".

I recently updated Rails to version 6.1.5, but the error persists. Any suggestions on how to resolve this issue?

Thank you.

**Comment by picman** [comment]
Probably duplicates #2 .

**Comment by 7evenk** [comment]
I had the issue with a Bitnami Redmine 5.0.0-2 installation, which used Ruby 2.6.10p210. I have now installed Redmine 5.0.5 and Ruby 3.1.4-1 under Windows. The plugin works perfectly with these versions. Thank you
