### ISSUE TITLE
0.2.2 IMAP VERSION

### ISSUE THREAD

**Issue by 1CMTdev** [kontron/redmine_oauth#13]
my imap version is 0.2.2, im using it for azure ad. Will it work? or do i need 0.3.1

**Comment by 1CMTdev** [comment]
thank u :)

**Comment by picman** [comment]
No, it won't. 0.3.1 is required.

**Comment by 1CMTdev** [comment]
Sorry im not that familiar with rubygems, but I cant somehow install 0.3.1 because it cant install date 3.3.3

**Comment by picman** [comment]
1. Comment out `gem 'net-imap', '~> 0.2.2'` inne in redmine/Gemfile
2. Then `cd redmine && bundle install
3. See the output and fix the errors. Google is your friend.
