### ISSUE TITLE
Is it possible for the plugin to work with the redmine(5.0.5)'s  2FA ?

### ISSUE THREAD

**Issue by CM4115** [kontron/redmine_oauth#15]
Tried to require every user to activate 2FA.
The 2FA **activation** works after the 1st login.
After that it doesnt require an auth code from the 2fa from every login of the user. It goes directly to the dashboard.

**Comment by picman** [comment]
You mean that OAuth plugin is installed and activated but a user uses the original Redmine login form with login and password and 2FA is not required despite it is set so in their account? Do you have any other plugins installed?

**Comment by CM4115** [comment]
OAuth plugin is installed and activated and the 2FA doesn't work. It automatically redirects to dashboard instead of requiring to 2FA. (the 2FA is activated and required for the user)  No, I don't have other plugins. Thank you for responding.

**Comment by picman** [comment]
If a user uses OAuth authentication, the authentication is completely handed over to the selected OAuth provider and all authentication settings in Redmine including 2FA are not taken into account/skipped.
