### ISSUE TITLE
What's the initial password for users created from Gitlab?

### ISSUE THREAD

**Issue by inlann** [kontron/redmine_oauth#19]
Hello,

Glad to find this awesome plugin! 🚀 

I created the OAuth2 application for my redmine in my Gitlab. And then, I deployed this plugin and configurated the plugin correctly in my redmine.

Finally, the plugins works!

I registered with my Gitlab account and signed in. But when I tried to change my password, I don't know where to find the current password: 

<img width="1066" alt="image" src="https://github.com/kontron/redmine_oauth/assets/33852855/8fdb4d5e-072b-48af-ae5f-3b438a236ece">

Any help? Really appreciate!

**Comment by picman** [comment]
If you use OAuth, the users are authenticated in GitLab. So their passwords are managed there.
If you still need to use Redmine authentication, e.g. for repositories access, you have to set up passwords in Redmine too. The initial password must be set by a Redmine administrator.

**Comment by inlann** [comment]
> If you use OAuth, the users are authenticated in GitLab. So their passwords are managed there. If you still need to use Redmine authentication, e.g. for repositories access, you have to set up passwords in Redmine too. The initial password must be set by a Redmine administrator.

Thanks for you reply!!

Users created by OAuth will have a login name and can log in with that name. However, their password is a [random password](https://github.com/kontron/redmine_oauth/blob/4be9a174aa57c4f112b6a9e3a1149eda2bda1313/app/controllers/redmine_oauth_controller.rb#L123). Therefore, they will fail to log in, and they cannot change the password.

Perhaps we can change the random password to a simple "123456" and ask users to change the password when they log in for the first time?

**Comment by picman** [comment]
The users can themself reset their passwords using "Lost password" link on the login page.
