### ISSUE TITLE
Using custom OIDC provider only prompts "authenticated"

### ISSUE THREAD

**Issue by sando38** [kontron/redmine_oauth#38]
Hello,
I configured redmine with the OIDC plugin, configured a custom OIDC provider ([Authentik](https://goauthentik.io/)). When I click on "sign in" and use the OIDC provider, I am correctly redirected, login and redirected back to redmine.

However, I only see this
![Screenshot 2024-05-19 133512](https://github.com/kontron/redmine_oauth/assets/90323876/f252fed5-2dd6-4c3d-b8f9-4b24c0d705b7)

This is my configuration:
![Screenshot 2024-05-19 134153](https://github.com/kontron/redmine_oauth/assets/90323876/c460eba3-b09f-4626-8ca7-8bdc5ba60847)

Scope and properaties like `preferred_username` and `email` are provided by the OIDC.

Do you have any idea how I could further debug? Any help is appreciated!

Thank you very much!

**Comment by picman** [comment]
Take a look into _log/production.log_.

**Comment by sando38** [comment]
Good morning @picman
Thanks for the quick reply. All good now. There was a conflicting rule in the reverse proxy configuration in my system.. Removed it and all good.
