### ISSUE TITLE
Decouple self-registration and OIDC registration

### ISSUE THREAD

**Issue by gramakri** [kontron/redmine_oauth#39]
OIDC registration creates new users (or not) based on redmine's self registration flag. This probably makes sense if OIDC provider is some social login provider (twitter, generic Google, GitHub etc).

This does not work for situations where the OIDC provider is for an internal Directory. For example, Keycloak, Authentik, Google Workspace etc. In such a set up, we want to disable redmine's self registration but want to enable login via the OIDC provider only.

I think having a plugin specific setting instead of using redmine's self registration flag would solve this.

https://github.com/kontron/redmine_oauth/issues/18 is related , I think

**Comment by gramakri** [comment]
@picman if you are open to it, we can submit a patch which add a setting which would replace the use of https://github.com/kontron/redmine_oauth/blob/main/app/controllers/redmine_oauth_controller.rb#L161

**Comment by picman** [comment]
Of course. Create a pull request to the _devel_ branch.

**Comment by picman** [comment]
Where is the patch?

**Comment by gramakri** [comment]
@picman ah, I missed your initial message. I can create a patch against devel tomorrow.

**Comment by sgrossberndt** [comment]
We at TYPO3 are missing the same feature. Great to hear there is already progress here. I will test this once a patch has been provided.

**Comment by gramakri** [comment]
@picman @sgrossberndt I have an initial patch working. Will test a bit more over the weekend and submit a PR. Comments welcome (I am not a ruby or a redmine dev!)

**Comment by gramakri** [comment]
@picman @sgrossberndt I have submitted a PR

**Comment by sgrossberndt** [comment]
Thanks, I did not receive a notification for the PR.
I will test it in the next days.

**Comment by picman** [comment]
Merged. You can test it.
