### ISSUE TITLE
RUBY0001 NO AUTHENTICATE failed.

### ISSUE THREAD

**Issue by kus6021** [kontron/redmine_oauth#4]
Hello,
I try to create an redmine ticket from an email and I have an authentication issue

my command is:
rake redmine_oauth:email:receive_imap RAILS_ENV="production" host=outlook.office365.com ssl=true username=XXXX@WWWWWW.com

the pluging seems correctly confirured and I have this message and I don't understant what is wrong:

** Invoke redmine_oauth:email:receive_imap (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_oauth:email:receive_imap
S: * OK The Microsoft Exchange IMAP4 service is ready. [UABSADAAUAAyADYANABDAEEAMAAxADcAMgAuAEYAUgBBAFAAMgA2ADQALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: RUBY0001 AUTHENTICATE XOAUTH2
S: +
C: dXNlcj1zdXBwb3J0LWRldkBuZWxsY2xvdWQuZXUBYXV0aD1CZWFyZXIgZXlKMGVYQWlPaUpLVjFRaUxDSnViMjVqWlNJNklqUlRVRmN3YUhSb01qUXhSR1ZrWDBwR1dGQjRjakJoUzB4WkxYWndZVk14ZVhsWFpGY3RiRlpPTkRnaUxDSmhiR2NpT2lKU1V6STFOaUlzSW5nMWRDSTZJaTFMU1ROUk9XNU9VamRpVW05bWVHMWxXbTlZY1dKSVdrZGxkeUlzSW10cFpDSTZJaTFMU1ROUk9XNU9VamRpVW05bWVHMWxXbTlZY1dKSVdrZGxkeUo5LmV5SmhkV1FpT2lKb2RIUndjem92TDI5MWRHeHZiMnN1YjJabWFXTmxNelkxTG1OdmJTSXNJbWx6Y3lJNkltaDBkSEJ6T2k4dmMzUnpMbmRwYm1SdmQzTXVibVYwTDJFMFpESTFOMll6TFRKaE9EQXROR0UwTUMxaFlUQTBMV0UyT1dNM01XVTRPR013WkM4aUxDSnBZWFFpT2pFMk56RTNNREl4TlRjc0ltNWlaaUk2TVRZM01UY3dNakUxTnl3aVpYaHdJam94TmpjeE56QTJNRFUzTENKaGFXOGlPaUpGTWxwbldVNW9jVmhFZUd4ME0xQjRMMjVYVUhZMVlWWmlSSGhtUkZGQlBTSXNJbUZ3Y0Y5a2FYTndiR0Y1Ym1GdFpTSTZJbk4xY0hCdmNuUXRaR1YySWl3aVlYQndhV1FpT2lJd01tVmtZMlJsWVMwNU5tSTFMVFEzTXpJdFlURTBOeTFpTlRBd056UTRNV1EwWlRNaUxDSmhjSEJwWkdGamNpSTZJakVpTENKcFpIQWlPaUpvZEhSd2N6b3ZMM04wY3k1M2FXNWtiM2R6TG01bGRDOWhOR1F5TlRkbU15MHlZVGd3TFRSaE5EQXRZV0V3TkMxaE5qbGpOekZsT0Roak1HUXZJaXdpYjJsa0lqb2lOalF3WXpZeFpXWXRaREZsT0MwME5qZGlMV0psTlRrdE5qVTVOREUwTVRVd05EbGtJaXdpY21naU9pSXdMa0ZVUlVFNE1XWlRjRWxCY1ZGRmNYRkNTMkZqWTJWcFRVUlJTVUZCUVVGQlFWQkZVSHBuUVVGQlFVRkJRVUZCZUVGQlFTNGlMQ0p5YjJ4bGN5STZXeUpWYzJWeUxsSmxZV1F1UVd4c0lpd2lablZzYkY5aFkyTmxjM05mWVhOZllYQndJaXdpVFdGcGJDNVNaV0ZrVjNKcGRHVWlMQ0pRVDFBdVFXTmpaWE56UVhOQmNIQWlMQ0pOWVdsc0xsSmxZV1FpTENKTllXbHNMbE5sYm1RaUxDSkpUVUZRTGtGalkyVnpjMEZ6UVhCd0lsMHNJbk5wWkNJNkltTTBaREZqTm1OakxXVTFPRFF0TkdGa01pMDVNR0V6TFRRd01UQmpNREppT1RaaE1DSXNJbk4xWWlJNklqWTBNR00yTVdWbUxXUXhaVGd0TkRZM1lpMWlaVFU1TFRZMU9UUXhOREUxTURRNVpDSXNJblJwWkNJNkltRTBaREkxTjJZekxUSmhPREF0TkdFME1DMWhZVEEwTFdFMk9XTTNNV1U0T0dNd1pDSXNJblYwYVNJNkltdHBNMEphYkhvM05GVkhhelZ1WWxWUGRGTklRVUVpTENKMlpYSWlPaUl4TGpBaUxDSjNhV1J6SWpwYklqQTVPVGRoTVdRd0xUQmtNV1F0TkdGallpMWlOREE0TFdRMVkyRTNNekV5TVdVNU1DSmRmUS5QZm85UXFTZWdXWkR5NkYxZ0ZOdWJNTnI2QXdkdHp5dkM3NlltMnM4NzlSamtMZVI2M3JaMDB1bTQwemdCZ2JzMjU1NmtuVXFBSzZaam9jSDhrdnNpQnB0djYxaE1rNDg2dlp4MHQ3ZWZiX2dPNHZvUWtEZXdlay1TSDVnNjYzcWpfeG5sSkgzQTVrdGNVX2EwQVZJYkRNNTRHUkkxOVl2OWdWNnhpQVVpS2R0aFYtRy1vRDhFdFJkTXAyc1dCWEpnRVc4YjN4RUphc1NjcUZIS3Q5bUFaRkNMVFFrbFJJTkhZdmhnSU5iZkdlY3lma0xXb2tzdHVlT2VEWk9SUjBfQ0FmVHpHWEhBUHlWTVJNZGVfaEltWkRfTFlmOU9NNDNJQ2x5cjZkRmJsNFMxMUdTcTNDMXMydEtiTGU5LS1xOUtUY250d0dIX1hVekVxRmtKNUFNTkEBAQ==
S: RUBY0001 NO AUTHENTICATE failed.
AUTHENTICATE failed.

please help me

Many thaks 
BR,
Mustapha

**Comment by picman** [comment]
Have you configured Azure AD according to https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#use-client-credentials-grant-flow-to-authenticate-imap-and-pop-connections ?

**Comment by picman** [comment]
Is access from another client using the same credentials working?

**Comment by kus6021** [comment]
Hello,
Happy 2023!!!
I tested another solution with the same Azure Ad configuration and it works with this solution.
I am looking for another way to use POP instead of IMAP.
Thanks for your help

BR,
Mustapha

**Comment by picman** [comment]
ok
