### ISSUE TITLE
Encrypt client_secret

### ISSUE THREAD

**Issue by Coolfeather2** [kontron/redmine_oauth#44]
Hi 

Is it possible to encrypt the `client_secret` in the plugin setting page and database (using `Redmine::Configuration['database_cipher_key']`)?

Redmine has this functionality within `AuthSource`, `Repository` and `User` Class, but does not look like its available for `Settings` Class

Ref: https://www.rubydoc.info/github/redmine/redmine/Redmine/Ciphering

**Comment by picman** [comment]
Implemented as follows. As soon as you set the `database_cipher_key` in _config/configuration.yml_, the `client_secret` is ciphered when you save the plugin's options and deciphered when you read them.
Could you test it with the _devel_ branch, please?

**Comment by Coolfeather2** [comment]
Working, thank you for your prompt work
