### ISSUE TITLE
[Custom OIDC Provider] Add configuration fields for mapping of firstname and lastname values

### ISSUE THREAD

**Issue by roto7** [kontron/redmine_oauth#45]
Hello,
First of all, thanks a lot for this great plugin! :)
My request is related to the use of a custom OIDC Provider, because in our organization we have to deal with the group IdP configuration (we're not able to ask for fields renaming). As a "quick-and-dirty" workaround, I've just modified few lines in the self-registration code section of `redmine_oauth_controller.rb` to match fields provided by our IdP:
```ruby
      user.firstname = info['givenName']
      user.lastname = info['sn']
```
...but it would be way cleaner if we could benefit from firstname and lastname mapping fields, just like "UID field" and "Email field".
Would that be possible?

Thanks in advance!
Best regards.

**Comment by picman** [comment]
Could you test it in the _devel_ branch please? Whether it is what you ask for?

**Comment by roto7** [comment]
Hello Karel,
I'm really sorry for my lack of answer, I've been on holidays for the last 3 weeks.
Many thanks for this new release, I'll try it ASAP.
Best regards.

**Comment by roto7** [comment]
Hello Karel,
I've just tested v2.2.4, and the behaviour is exactly what I was looking for! 👍 
Thank you!
