### ISSUE TITLE
Auth0 support

### ISSUE THREAD

**Issue by yunylz** [kontron/redmine_oauth#47]
As the title says, any possibility for this?

**Comment by picman** [comment]
Any links what it is and where and how to test it?

**Comment by yunylz** [comment]
> Any links what it is and where and how to test it?

https://auth0.com/docs/api/authentication

**Comment by picman** [comment]
Can't be the [Custom OIDC provider](#24) used here?

**Comment by picman** [comment]
By the way Auth0 is provided by Okta, that is already supported. Can you try that?

**Comment by picman** [comment]
No feedback => closing
