### ISSUE TITLE
Install problem - Kubernetes + image redmine (dockerhub)

### ISSUE THREAD

**Issue by nakladalm** [kontron/redmine_oauth#49]
Hello, 
i have a problem with installation into a clean workspace (after installing the first operation)

Version:
`
Environment:
  Redmine version                5.1.3.stable
  Ruby version                   3.2.5-p208 (2024-07-26) [x86_64-linux]
  Rails version                  6.1.7.8
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Classic
SCM:
  Subversion                     1.14.2
  Mercurial                      6.3.2
  Bazaar                         3.3.2
  Git                            2.39.2
  Filesystem                     
Redmine plugins:
  no plugin installed
`

Error:

`

root@redmine-6549776f54-nt8g4:/usr/src/redmine/plugins# git clone https://github.com/kontron/redmine_oauth.git
Cloning into 'redmine_oauth'...
remote: Enumerating objects: 984, done.
remote: Counting objects: 100% (265/265), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 984 (delta 208), reused 216 (delta 176), pack-reused 719
Receiving objects: 100% (984/984), 1.82 MiB | 4.91 MiB/s, done.
Resolving deltas: 100% (488/488), done.
root@redmine-6549776f54-nt8g4:/usr/src/redmine/plugins# chown -R www-data:www-data redmine_oauth
root@redmine-6549776f54-nt8g4:/usr/src/redmine/plugins# cd ../
root@redmine-6549776f54-nt8g4:/usr/src/redmine# bundle install
Your Gemfile lists the gem puma (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching faraday 2.10.1
Installing faraday 2.10.1
Installing bigdecimal 3.1.8 with native extensions
Bundler::DirectoryRemovalError: Could not delete previous installation of `/usr/local/bundle/gems/bigdecimal-3.1.8`.
The underlying error was ArgumentError: parent directory is world writable, Bundler::FileUtils#remove_entry_secure does not work; abort: "/usr/local/bundle/gems/bigdecimal-3.1.8" (parent directory
mode 40777), with backtrace:
  /usr/local/lib/ruby/3.2.0/bundler/vendor/fileutils/lib/fileutils.rb:1387:in `remove_entry_secure'
  /usr/local/lib/ruby/3.2.0/bundler.rb:332:in `rm_rf'
  /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:111:in `strict_rm_rf'
  /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:19:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/source/rubygems.rb:202:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

Bundler Error Backtrace:
  /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:115:in `rescue in strict_rm_rf'
  /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:110:in `strict_rm_rf'
  /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:19:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/source/rubygems.rb:202:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing bigdecimal (3.1.8), and Bundler cannot continue.

In Gemfile:
  oauth2 was resolved to 2.0.9, which depends on
    multi_xml was resolved to 0.7.1, which depends on
      bigdecimal

`

**Comment by picman** [comment]
> Could not delete previous installation of /usr/local/bundle/gems/bigdecimal-3.1.8
Check the permissions. Remove the folder manually prior `bundle install`?

**Comment by nakladalm** [comment]
Yes! Thank you ! 

just update the packages, thanks a lot

**Comment by nakladalm** [comment]
For other...

`#  BASE Img
FROM redmine:latest

# Updating packages and system dependencies
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev

RUN rm -rf /usr/local/bundle/cache
RUN bundle clean --force


# OAuth - Picman
RUN cd /usr/src/redmine/plugins \
    && git clone https://github.com/kontron/redmine_oauth.git

RUN chown -R redmine:redmine /usr/src/redmine/plugins

RUN cd /usr/src/redmine \
    && bundle install --without development test



# RUN
CMD ["rails", "server", "-b", "0.0.0.0"]
`
