### ISSUE TITLE
Text is spanish by default

### ISSUE THREAD

**Issue by gramakri** [kontron/redmine_oauth#51]
I guess this is a typo in https://github.com/kontron/redmine_oauth/blob/2f0183d086170877a20357977015853fdba42709/config/locales/es.yml#L21 ? It should 'es' maybe?

![image](https://github.com/user-attachments/assets/0f6e7099-50f1-4423-a3a8-68d44a0c36b4)

**Comment by picman** [comment]
Fixed. Thank you!
