### ISSUE TITLE
Allowed domains feature

### ISSUE THREAD

**Issue by tuzumkuru** [kontron/redmine_oauth#54]
I’d like to request a feature that allows restricting OAuth logins to specific domains. Currently, the plugin allows logins from any domain, but adding a configuration option for Allowed Domains would be very useful, especially for organizations using Google Workspace accounts. I am not sure if it applies to other methods than Google. 

Use case: In our organization, we use Google Workspace, and it would be helpful to restrict OAuth logins to only our company’s domain. This would enhance security by ensuring that only users with company email addresses can log in. 

Proposed Solution: Add a textbox in the plugin configuration to define allowed domains line by line. The plugin would then only allow OAuth logins from the specified domains.

Thank you for considering this feature.

**Comment by col-panic** [comment]
@tuzumkuru Couldn't you solve this scenario using the IdP? That is you could add a role to your authentication server, that does not hand out tokens for this service if you are not part of the specific domain.

In Keycloak, for example, you could modify configure a specific `Authentication Flow` for your client, which during authentication would check the domain of the user. So while this CAN be done by the client, i guess it could also be done by the IdP!

**Comment by tuzumkuru** [comment]
I could do it using Google Workspace but in Gmail (Google personal account) even there is that option set, it accepted all domains. I couldn't restrict. 
I saw this type of workflow (restriction in plugin) in another old OAuth plugin so thought it could have some use. 
I agree with you on if it is a common feature of IdP's it should stay like the way it is now.

**Comment by sh1nj1** [comment]
@col-panic You can do this in Google

Set User Type as Internal in OAuth content screen.
In this mode, your app is limited to Google Workspace users within your organisation.

**Comment by tuzumkuru** [comment]
> @col-panic You can do this in Google
> 
> Set User Type as Internal in OAuth content screen. In this mode, your app is limited to Google Workspace users within your organisation.

As I said in the previous comment, it can be done in Google Workspace but not when using personel google account for Google Cloud. 

Still that workflow does not make sense for me either. 

We can close this issue.
