### ISSUE TITLE
Questions about Docker installation

### ISSUE THREAD

**Issue by dmaia-avivar** [kontron/redmine_oauth#58]
I'm setting up a connection to Azure ID, and I currently use Redmine Docker - the point is, I use docker-compose. How am I supposed to configure what you required if I don't edit the Dockerfile?

Anyway, I tried using it without doing this part, and it works - until some point. The app asks to autheticate after you login, and it autheticates properly on Azure - but Redmine returns incorrect user or password. If it was incorrect, not even Microsft was supposed to go on with the authentication, right? And I'm sure the credentials are correct.
Could it be because of this step?

FROM redmine:latest

Fix permissions for bundle install of bigdecimal for redmine_oauth
RUN chown -R redmine: /usr/local/bundle/ && chmod -R o-w /usr/local/bundle/

Install build-essential to build dependencies of redmine_oauth
RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get install --yes --no-install-recommends build-essential \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

Could it be a configuration in the Administration -> Configuration -> Authentication?
Can you help?

**Comment by picman** [comment]
Take a look into _log/production.log_ for any errors related to a unsuccessful login.
