### ISSUE TITLE
ADFS - No verified email provided

### ISSUE THREAD

**Issue by unbeatable27** [kontron/redmine_oauth#67]
Need help figuring out an error against ADFS: No verified email provided, check your settings on OAuth provider site. I was able to get it working against wso2 IDP but getting error against ADFS

I, [2024-12-12T13:36:32.894304 #2915741]  INFO -- : [220a73b2-0afb-403a-a8c5-c812b23367d5] Completed 302 Found in 50ms (ActiveRecord: 3.9ms | Allocations: 32279)
I, [2024-12-12T13:36:33.014481 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87] Started GET "/oauth2callback?code=AAAAAAAAAAAAAAAAAAAAAA.zS_b5tsa3QigF2S8pET3gMTsZd4.QvrAfGvc57vVXitm_UkruOKRSW2DcGehwSQeyghFw1trqgkO2nL9iy6fEQhu9_3Uw6iU02nhWGDEI_o6KJBdFNlh2EbGYGC8zarujqNA9YKFSSw-AUXBQR6lfutiJjm_1PzV3R80z33H7PFGBin1UCIIaiqYIRh61tUOCL4XVaZcEvo3LUkOwU-0cMPi6QVrx0_cMVFEYH80RIyZdw21FX9r1IlEhuaLGjRChVEroWnt2Mh1ltVH7QwTPm2y7Hajqqjfiu1hblwUB7Ik3teawP9ZAzzrwKnEr-zXFuBPO44UcGwrNbi2RrUAUMtMKDbNRxZHpOvnyHvJA-dES4wBNg&state=juTjsHN7ufR3IVKI204TQjPGig8XXQBpNAEb/PLJH9M=" for 10.50.94.37 at 2024-12-12 13:36:33 -0500
I, [2024-12-12T13:36:33.015069 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87] Processing by RedmineOauthController#oauth_callback as HTML
I, [2024-12-12T13:36:33.015109 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87]   Parameters: {"code"=>"AAAAAAAAAAAAAAAAAAAAAA.zS_b5tsa3QigF2S8pET3gMTsZd4.QvrAfGvc57vVXitm_UkruOKRSW2DcGehwSQeyghFw1trqgkO2nL9iy6fEQhu9_3Uw6iU02nhWGDEI_o6KJBdFNlh2EbGYGC8zarujqNA9YKFSSw-AUXBQR6lfutiJjm_1PzV3R80z33H7PFGBin1UCIIaiqYIRh61tUOCL4XVaZcEvo3LUkOwU-0cMPi6QVrx0_cMVFEYH80RIyZdw21FX9r1IlEhuaLGjRChVEroWnt2Mh1ltVH7QwTPm2y7Hajqqjfiu1hblwUB7Ik3teawP9ZAzzrwKnEr-zXFuBPO44UcGwrNbi2RrUAUMtMKDbNRxZHpOvnyHvJA-dES4wBNg", "state"=>"juTjsHN7ufR3IVKI204TQjPGig8XXQBpNAEb/PLJH9M="}
D, [2024-12-12T13:36:33.016148 #2915741] DEBUG -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87]   ^[[1m^[[35m (0.2ms)^[[0m  ^[[1m^[[34mSELECT MAX(`settings`.`updated_on`) FROM `settings`^[[0m
D, [2024-12-12T13:36:33.016876 #2915741] DEBUG -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87]   ^[[1m^[[36mAnonymousUser Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT `users`.* FROM `users` WHERE `users`.`type` = 'AnonymousUser' AND `users`.`lastname` = 'Anonymous' LIMIT 1^[[0m
I, [2024-12-12T13:36:33.017023 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87]   Current user: anonymous
I, [2024-12-12T13:36:33.089490 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87] >>> email
I, [2024-12-12T13:36:33.089524 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87] >>>
I, [2024-12-12T13:36:33.089549 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87] >>> {"sub"=>"9fPa/z6sGxg2gEuyBm3Ekydfn9tIKaE5LwhWt0JLpxo=", "login"=>nil}
E, [2024-12-12T13:36:33.089934 #2915741] ERROR -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87] No verified email provided, check your settings on OAuth provider site.
I, [2024-12-12T13:36:33.090202 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87] Redirected to https://devredmine.<domain.com>/login
I, [2024-12-12T13:36:33.090312 #2915741]  INFO -- : [2c7014b0-9b8d-4c1c-bff1-cca70744db87] Completed 302 Found in 75ms (ActiveRecord: 0.4ms | Allocations: 5357)
I, [2024-12-12T13:36:33.101632 #2915741]  INFO -- : [c8dd2578-7d39-4148-aad6-7d37199b3816] Started GET "/login" for 10.xx.xx.xx at 2024-12-12 13:36:33 -0500
I, [2024-12-12T13:36:33.102138 #2915741]  INFO -- : [c8dd2578-7d39-4148-aad6-7d37199b3816] Processing by AccountController#login as HTML
D, [2024-12-12T13:36:33.103253 #2915741] DEBUG -- : [c8dd2578-7d39-4148-aad6-7d37199b3816]   ^[[1m^[[35m (0.2ms)^[[0m  ^[[1m^[[34mSELECT MAX(`settings`.`updated_on`) FROM `settings`^[[0m

![image](https://github.com/user-attachments/assets/b6d2e9eb-bf0b-4da5-bc18-8731bea1e0f8)

**Comment by picman** [comment]
The response from OAuth provider probably doesn't contain the user's email. Check **OAuth scope** and **UID field** options. When a response on an authentication request comes, it is expected that the user's email is present as the UID field.
What version of OAuth plugin do you use?
Where did ">>>" in the log come from?
If you have some programming skills add some log messages into _app/controllers/redmine_oauth_controller.rb_ `RedmineOauthController::oauth_callback` to the part where the email is being got:
```ruby
when 'Custom'
      token = oauth_client.auth_code.get_token(params['code'], redirect_uri: oauth_callback_url)
      if RedmineOauth.custom_profile_endpoint.empty?
        user_info = JWT.decode(token.token, nil, false).first
      else
        userinfo_response = token.get(
          RedmineOauth.custom_profile_endpoint,
          headers: { 'Accept' => 'application/json' }
        )
        user_info = JSON.parse(userinfo_response.body)
      end
      Rails.logger.info ">>> #{user_info}" # Added log message
      user_info['login'] = user_info[RedmineOauth.custom_uid_field]
      email = user_info[RedmineOauth.custom_email_field]
      Rails.logger.info ">>> #{email}" # Added log message
    else
```

**Comment by unbeatable27** [comment]
Plugin version is 2.2.8.  The >>> came from below code where the logger was added as per your suggestion in issue57 that had the same error:
 when 'Custom'
      token = oauth_client.auth_code.get_token(params['code'], redirect_uri: oauth_callback_url)
      if Setting.plugin_redmine_oauth[:custom_profile_endpoint].strip.empty?
        user_info = JWT.decode(token.token, nil, false).first
      else
        userinfo_response = token.get(
          Setting.plugin_redmine_oauth[:custom_profile_endpoint],
          headers: { 'Accept' => 'application/json' }
        )
        user_info = JSON.parse(userinfo_response.body)
      end
      user_info['login'] = user_info[Setting.plugin_redmine_oauth[:custom_uid_field]]
      email = user_info[Setting.plugin_redmine_oauth[:custom_email_field]]
      Rails.logger.info ">>> #{Setting.plugin_redmine_oauth[:custom_email_field]}"
      Rails.logger.info ">>> #{email}"
      Rails.logger.info ">>> #{user_info}"

**Comment by picman** [comment]
Try to delete the value in **Profile endpoint** in the plugin's settings and leave it empty.

**Comment by picman** [comment]
The problems is that each OAuth provider sends the token in different format. This field distinguish between Json Web Token and JavaScript object notation format in case of _Custom_ provider.
