### ISSUE TITLE
Redirect URL sent to Azure AD starts with http

### ISSUE THREAD

**Issue by sabinfos** [kontron/redmine_oauth#68]
Hi,

I configured the plugin for Azure AD authentication using OAuth v2

It looks the redirect URL sends by the plugin starts with http instead of https (I see the same result with OAuth v1).

```
Microsoft 365 error:
Request Id: 7a496bfe-<truncated>
Correlation Id: 5ac98c2b-<truncated>
Timestamp: 2024-12-27T10:24:44Z
Message: AADSTS50011: The redirect URI 'http://redmine.<mydomain>/oauth2callback' specified in the request does not match the redirect URIs configured for the application 'ed6a2fc3-<truncated>'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

```
Redmine logs
```
I, [2024-12-26T10:24:44.855528 #1] INFO -- : [686cafed-<truncated>] Started GET "/" for 192.168.9.6 at 2024-12-27 10:24:44 +0000
I, [2024-12-26T10:24:44.856110 #1] INFO -- : [686cafed-<truncated>] Processing by WelcomeController#index as HTML
I, [2024-12-26T10:24:44.884716 #1] INFO -- : [686cafed-<truncated>]  Current user: anonymous
I, [2024-12-26T10:24:44.885397 #1] INFO -- : [686cafed-<truncated>] Redirected to http://redmine.<mydomain>/login?back_url=http%3A%2F%2Fredmine.<mydomain>%2F
I, [2024-12-26T10:24:44.885506 #1] INFO -- : [686cafed-<truncated>] Filter chain halted as :check_if_login_required rendered or redirected
I, [2024-12-26T10:24:44.885690 #1] INFO -- : [686cafed-<truncated>] Completed 302 Found in 29ms (ActiveRecord: 30.8ms (2 queries, 0 cached) | GC: 0.0ms)
I, [2024-12-26T10:24:45.799423 #1] INFO -- : [9ee28a66-<truncated>] Started GET "/login?back_url=http%3A%2F%2Fredmine.<mydomain>%2F" for 172.31.9.6 at 2
024-12-27 10:24:45 +0000
I, [2024-12-26T10:24:45.800067 #1] INFO -- : [9ee28a66-<truncated>] Processing by AccountController#login as HTML
I, [2024-12-26T10:24:45.800111 #1] INFO -- : [9ee28a66-<truncated>]  Parameters: {"back_url"=>"http://redmine.<mydomain>/"}
I, [2024-12-26T10:24:45.802886 #1] INFO -- : [9ee28a66-<truncated>]  Current user: anonymous
I, [2024-12-26T10:24:45.813440 #1] INFO -- : [9ee28a66-<truncated>]  Rendered layout layouts/base.html.erb (Duration: 9.9ms | GC: 0.0ms)
I, [2024-12-26T10:24:45.813748 #1] INFO -- : [9ee28a66-<truncated>] Completed 200 OK in 13ms (Views: 10.3ms | ActiveRecord: 0.8ms (2 queries, 0 cached) | GC: 0.0ms)
```

The redirect URI configured for Redmine instance in Entra ID application is the following : `https://redmine.<mydomain>/oauth2callback`

Any advice for configuring the plugin?

Below some technical background related to the architecture :
Redmine is running into a container behind a reverse proxy that offload TLS connections.
In Redmine settings : `redmine.<mydomain>` is configured in "Host name and path" section and `HTTPS` is configured in "Protocol" section.

My configuration is the following :
Debian 12.8
Docker 27.4.1
Redmine 6.0.2 image (last dockerhub version)
Postgres 17.2-bookworm image
Httpd 2.4.62-bookworm image, customized for reverse proxy modules activation

There is a bridge network between the reverse proxy container and the Redmine container.
Only the port 443 is exposed by the reverse proxy.
Default Redmine configuration is used (http on port 3000).

The reverse proxy configuration is the following : 
```
<VirtualHost *:443>
 ServerName redmine.<mydomain>
 ErrorLog logs/redmine_error_ssl.log    
 CustomLog logs/redmine_access_ssl.log combined   

 HostnameLookups Off
 ServerSignature Off

 SSLEngine on
 SSLCertificateFile /opt/reverse/redmine/redmine.crt
 SSLCertificateKeyFile /opt/reverse/redmine/redmine.key
 SSLProtocol -all +TLSv1.2
 SSLHonorCipherOrder on
 SSLCompression   off
 SSLSessionTickets  off

 <Location />
  Order allow,deny
  Allow from all
  ProxyPass http://redmine_app:3000/
  ProxyPassReverse http://redmine_app:3000/
 </Location>
</VirtualHost>
```

Excluding this plugin, all Redmine features work fine.
I have multiple containers running in the same docker instance and also behind the same reverse proxy with an OAuth authentication with Entra ID that work fine.

**Comment by picman** [comment]
Check Administation -> Settings -> General -> Protocol: "HTTPS"

**Comment by sabinfos** [comment]
Thanks for the answer: HTTPS protocol is already configured in Redmine Settings
![image](https://github.com/user-attachments/assets/0504dcf1-eb10-428b-a925-f1fd20e73f0b)

**Comment by sh1nj1** [comment]
Adding `X-Forwarded-Ssl: on` or `X-Forwarded-Proto: https` headers from proxy server will work.
 I got same issue with AWS CloudFront, I fixed it by sending `X-Forwarded-Ssl: on` header to origin server(redmine)
 
 - https://www.redmine.org/issues/40490
 - https://github.com/rack/rack/blob/e9f2f246377da9d1c1cb55dae4328273ef235488/lib/rack/request.rb#L249

**Comment by sabinfos** [comment]
> Adding `X-Forwarded-Ssl: on` or `X-Forwarded-Proto: https` headers from proxy server will work. I got same issue with AWS CloudFront, I fixed it by sending `X-Forwarded-Ssl: on` header to origin server(redmine)
> 
> * https://www.redmine.org/issues/40490
> * https://github.com/rack/rack/blob/e9f2f246377da9d1c1cb55dae4328273ef235488/lib/rack/request.rb#L249

It works like a charm.
Thanks for the quick answer.
