### ISSUE TITLE
Oauth2 for SMTP?

### ISSUE THREAD

**Issue by DolezalDavid** [kontron/redmine_oauth#7]
Hi Karel,
I've problem with sending notification via Offce365 SMTP server. Is your plugin also for SMTP authentification (sending) or only for IMAP (downloading)? 

David

**Comment by picman** [comment]
IMAP only. Concerning SMTP, in Azure, we implemented [SMTP Relay](https://learn.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#option-3-configure-a-connector-to-send-mail-using-microsoft-365-or-office-365-smtp-relay). There is nothing to be done on the client's side, just change the smart host to the SMTP relay created in the previous step.

**Comment by DolezalDavid** [comment]
"... in previous step." I don't understand what do you mean with it .. :-( Can you explain me please?

**Comment by DolezalDavid** [comment]
> "... in previous step." I don't understand what do you mean with it .. :-( Can you explain me please?

If I'm correct, SMTP relay send emails only inside the organisation, no outside. That can be problem us... Am I correct?

**Comment by picman** [comment]
No, SMTP Relay works for external emails too. From the guide: "You can't use direct send (Option 2) because you must send email to external recipients." => Option 3.

So:
1. Configure SMTP Relay in Azure AD => yourdomain.mail.protection.outlook.com
2. Configure Redmine to use this smarthost in *config/configuration.yml*:
```
production:
   email_delivery:
     delivery_method: :smtp
     smtp_settings:
       address: yourdomain.mail.protection.outlook.com
       port: 25
```

**Comment by DolezalDavid** [comment]
Thank you, Karel. I tested it and it send me back an error. 550 5.7.606 Access denied, banned sending IP. To request removal from this list please visit https://sender.office.com/ and follow the directions. For more information please go to http://go.microsoft.com/fwlink/?LinkID=526655 AS(1430) [HE1EUR01FT041.eop-EUR01.prod.protection.outlook.com 2023-02-21T08:49:13.098Z 08DB13563DBFD023] )

Do I need to setup in configuration.yml an e-mail or just what you sent in last post?

**Comment by picman** [comment]
Just what is set in the last post. The sending email address is set in Redmine administration.

> Thank you, Karel. I tested it and it send me back an error. 550 5.7.606 Access denied, banned sending IP. To request removal from this list please visit https://sender.office.com/ and follow the directions.

It seems, that IP of your server is on a black list...
